package:
    name: poropyck
    version: "{{ load_setup_py_data().version }}"

source:
    path: .

build:
    script: python setup.py install 

requirements:
    build:
        - python
        - dtw >=1.0.2
        - mcerp3
        - matplotlib <2.2
        - numpy
        - scipy
        - pyyaml
        - setuptools

    run:
        - python
        - dtw >=1.0.2
        - mcerp3
        - matplotlib <2.2
        - numpy
        - scipy

test:
    requires:
        - python
        - dtw >=1.0.2
        - mcerp3
        - matplotlib <2.2
        - numpy
        - scipy
    import:
        - poropyck

about:
    home: https://github.com/paul-freeman/poropyck
    license: GPL
    license_file: LICENSE
