package:
    name: poropyck
    version: "{{ load_setup_py_data().version }}"

source:
    path: .

build:
    noarch: python
    script: python setup.py install 

requirements:
    build:
        - python
        - uncertainties
        - matplotlib
        - numpy
        - scipy
        - pyyaml
        - setuptools

    run:
        - python
        - uncertainties
        - matplotlib
        - numpy
        - scipy

test:
    requires:
        - python
        - uncertainties
        - matplotlib
        - numpy
        - scipy
    import:
        - poropyck

about:
    home: https://github.com/paul-freeman/poropyck
    license: GPL
    license_file: LICENSE
